template: Hello, %s!

defaultName: Stranger

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8083
  adminConnectors:
    - type: http
      port: 9181